---
title: Research &amp; Development Engineer
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
url: http://junlulocky.com
baseurl: ''
yourname: Dr. George Krait
location: Nancy, France
facebook: https://www.facebook.com/george.krait/
linkedin: https://www.linkedin.com/in/george-krait-b86a3958/
github: https://github.com/gkrait/
