
title: My Resume
url: 'http://junlulocky.com'
baseurl: '/PanelCV' #change it according to your repository name



# Profile information
yourname: Dr. George Krait  ## put your name
title: 'Research &amp; Development Engineer'  ## your title
location: Nancy, France


## Social Profiles
facebook: https://www.facebook.com/george.krait/ ## your facebook account url
linkedin: https://www.linkedin.com/in/george-krait-b86a3958/  ## your linkedin account url
github: https://github.com/gkrait/ ## you dribbble account url



# Update all the sections by editing the files inside _includes folder.
